### ISSUE TITLE
Docker File - exit status 1: python setup.py egg_info

### ISSUE THREAD

**Issue by samhodgkinson** [DataDog/datadog-sync-cli#138]
**Overview of issue:**

**Steps to reproduce the issue:**

Clone the project repo and CD into the directory git clone https://github.com/DataDog/datadog-sync-cli.git; cd datadog-sync-cli
Build the probided Dockerfile docker build . -t datadog-sync
followed from https://github.com/DataDog/datadog-sync-cli

**Describe the results you received:**

 => ERROR [3/4] RUN pip install /datadog-sync-cli                                                                                                        3.3s
------
 > [3/4] RUN pip install /datadog-sync-cli:
#0 1.260 WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
#0 1.260 distutils: /usr/local/include/python3.9/UNKNOWN
#0 1.260 sysconfig: /usr/local/include/python3.9
#0 1.260 WARNING: Additional context:
#0 1.260 user = False
#0 1.260 home = None
#0 1.260 root = None
#0 1.260 prefix = None
#0 1.306 Processing /datadog-sync-cli
#0 1.306   DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
#0 1.306    pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
#0 2.984     ERROR: Command errored out with exit status 1:
#0 2.984      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7_t1vd4g/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7_t1vd4g/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-z1paamdz
#0 2.984          cwd: /tmp/pip-req-build-7_t1vd4g/
#0 2.984     Complete output (51 lines):
#0 2.984     running egg_info
#0 2.984     creating /tmp/pip-pip-egg-info-z1paamdz/datadog_sync_cli.egg-info
#0 2.984     writing /tmp/pip-pip-egg-info-z1paamdz/datadog_sync_cli.egg-info/PKG-INFO
#0 2.984     writing dependency_links to /tmp/pip-pip-egg-info-z1paamdz/datadog_sync_cli.egg-info/dependency_links.txt
#0 2.984     writing entry points to /tmp/pip-pip-egg-info-z1paamdz/datadog_sync_cli.egg-info/entry_points.txt
#0 2.984     writing requirements to /tmp/pip-pip-egg-info-z1paamdz/datadog_sync_cli.egg-info/requires.txt
#0 2.984     writing top-level names to /tmp/pip-pip-egg-info-z1paamdz/datadog_sync_cli.egg-info/top_level.txt
#0 2.984     writing manifest file '/tmp/pip-pip-egg-info-z1paamdz/datadog_sync_cli.egg-info/SOURCES.txt'
#0 2.984     Traceback (most recent call last):
#0 2.984       File "<string>", line 1, in <module>
#0 2.984       File "/tmp/pip-req-build-7_t1vd4g/setup.py", line 8, in <module>
#0 2.984         setup()
#0 2.984       File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
#0 2.984         return distutils.core.setup(**attrs)
#0 2.984       File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
#0 2.984         dist.run_commands()
#0 2.984       File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
#0 2.984         self.run_command(cmd)
#0 2.984       File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
#0 2.984       File "/usr/local/lib/python3.9/distutils/dist.py", line 857, in get_command_obj
#0 2.984         klass = self.get_command_class(command)
#0 2.984       File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 790, in get_command_class
#0 2.984         self.cmdclass[command] = cmdclass = ep.load()
#0 2.984       File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2450, in load
#0 2.984         return self.resolve()
#0 2.984       File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2456, in resolve
#0 2.984         module = __import__(self.module_name, fromlist=['__name__'], level=0)
#0 2.984     ModuleNotFoundError: No module named 'setuptools.command.build'
#0 2.984     ----------------------------------------
#0 2.984 WARNING: Discarding file:///datadog-sync-cli. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#0 2.985 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#0 3.243 WARNING: You are using pip version 21.1; however, version 23.1.2 is available.
#0 3.243 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
Dockerfile:5
--------------------
   3 |     # Install CLI
   4 |     COPY . /datadog-sync-cli
   5 | >>> RUN pip install /datadog-sync-cli
   6 |
   7 |     VOLUME ["/datadog-sync"]
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install /datadog-sync-cli" did not complete successfully: exit code: 1

**Describe the results you expected:**

The container build to load without errors. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by skarimo** [comment]
Thanks for the report. This is resolved by #139
