### ISSUE TITLE
Not compiled with python 3.9 or 3.10

### ISSUE THREAD

**Issue by Derek-Xiang** [DataDog/datadog-sync-cli#145]
**Overview of issue:**
The tool does not compile with python 3.9 or 3.10.

**Steps to reproduce the issue:**
1. Using python 3.9 or 3.10
2. pip install .

**Describe the results you received:**
datadog-sync ModuleNotFoundError: No module named 'pyimod02_importers'

**Describe the results you expected:**
Successfully installed and working properly.

**Comment by therve** [comment]
Hi, 
Can you describe your environment a bit more? This looks like a pyinstaller problem, but you don't mention using it. What's OS, are you using a git checkout, a tarball? Thanks.

**Comment by Derek-Xiang** [comment]
Hi @therve , my OS: MacBook Pro (16-inch, 2021).
I installed python 3.9 and 3.10 with pyenv, and both of them got that issue, but the docker version works fine, whose python is python 3.11.4, so I install python 3.11.0 with pyenv, and it works good, so I thought that is the problem.

**Comment by therve** [comment]
Can you try to upgrade pip to the latest version?

**Comment by Derek-Xiang** [comment]
Upgrading pip works, interesting. Thanks

**Comment by therve** [comment]
No problem, thank yoiu!
