### ISSUE TITLE
Failed to build docker image

### ISSUE THREAD

**Issue by abbasalizaidi** [DataDog/datadog-sync-cli#150]
**Fail to build docker image**

**Steps to reproduce the issue:**
1. Clone the repository
2. Run docker build . -t docker-sync

**Errors**

` => ERROR [3/4] RUN pip install /datadog-sync-cli                                3.5s
------
 > [3/4] RUN pip install /datadog-sync-cli:
#6 1.063 Processing /datadog-sync-cli
#6 1.064   Preparing metadata (setup.py): started
#6 3.356   Preparing metadata (setup.py): finished with status 'error'
#6 3.359   error: subprocess-exited-with-error
#6 3.359
#6 3.359   × python setup.py egg_info did not run successfully.
#6 3.359   │ exit code: 1
#6 3.359   ╰─> [49 lines of output]
#6 3.359       /usr/local/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
#6 3.359         warnings.warn(
#6 3.359       Traceback (most recent call last):
#6 3.359         File "<string>", line 2, in <module>
#6 3.359         File "<pip-setuptools-caller>", line 34, in <module>
#6 3.359         File "/datadog-sync-cli/setup.py", line 28, in <module>
#6 3.359           setup(
#6 3.359         File "/usr/local/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
#6 3.359           return distutils.core.setup(**attrs)
#6 3.359                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#6 3.359         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 147, in setup
#6 3.359           _setup_distribution = dist = klass(attrs)
#6 3.359                                        ^^^^^^^^^^^^
#6 3.359         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 476, in __init__
#6 3.359           _Distribution.__init__(
#6 3.359         File "/usr/local/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 282, in __init__
#6 3.359           self.finalize_options()
#6 3.359         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 900, in finalize_options
#6 3.359           ep(self)
#6 3.359         File "/usr/local/lib/python3.11/site-packages/setuptools/dist.py", line 920, in _finalize_setup_keywords
#6 3.359           ep.load()(self, ep.name, value)
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/integration.py", line 91, in version_keyword
#6 3.359           _assign_version(dist, config)
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/integration.py", line 60, in _assign_version
#6 3.359           maybe_version = _get_version(config)
#6 3.359                           ^^^^^^^^^^^^^^^^^^^^
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/__init__.py", line 153, in _get_version
#6 3.359           parsed_version = _do_parse(config)
#6 3.359                            ^^^^^^^^^^^^^^^^^
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/__init__.py", line 87, in _do_parse
#6 3.359           parse_result = _call_entrypoint_fn(config.absolute_root, config, config.parse)
#6 3.359                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/_entrypoints.py", line 49, in _call_entrypoint_fn
#6 3.359           return fn(root)
#6 3.359                  ^^^^^^^^
#6 3.359         File "/datadog-sync-cli/setup.py", line 25, in parse_fetch_on_shallow
#6 3.359           return parse(root, pre_parse=fetch_on_shallow)
#6 3.359                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/git.py", line 179, in parse
#6 3.359           wd = get_working_directory(config)
#6 3.359                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/git.py", line 164, in get_working_directory
#6 3.359           return GitWorkdir.from_potential_worktree(config.absolute_root)
#6 3.359                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/git.py", line 54, in from_potential_worktree
#6 3.359           require_command(cls.COMMAND)
#6 3.359         File "/datadog-sync-cli/.eggs/setuptools_scm-7.1.0-py3.11.egg/setuptools_scm/utils.py", line 171, in require_command
#6 3.359           raise OSError("%r was not found" % name)
#6 3.359       OSError: 'git' was not found
#6 3.359       [end of output]
#6 3.359
#6 3.359   note: This error originates from a subprocess, and is likely not a problem with pip.
#6 3.360 error: metadata-generation-failed
#6 3.360
#6 3.360 × Encountered error while generating package metadata.
#6 3.360 ╰─> See above for output.
#6 3.360
#6 3.360 note: This is an issue with the package mentioned above, not pip.
#6 3.360 hint: See above for details.
------
executor failed running [/bin/sh -c pip install /datadog-sync-cli]: exit code: 1`

**Expected output**
It should successfully build docker image

**Note** 
Looks like a dependency is missing `git`.

**Comment by skarimo** [comment]
Thanks for creating the PR including the fix. It has been merged
