### ISSUE TITLE
README/help output have unclear information about CLI options.

### ISSUE THREAD

**Issue by tobz** [DataDog/datadog-sync-cli#215]
(to be fleshed out further)

Currently, the help output in the README demonstrates the CLI flags as being global options, regardless of subcommand. This is not the case, and trying to pass them as global options results in error messages about the options being unknown.

We should, ideally:

- clean up the help output itself to show the command line usage as something closer to `datadog-sync [global options] [command] [options] [args]`
- remove the help text in the README itself, since it's a lot of extra noise and is at risk of falling out of sync with the actual help output.

**Comment by skarimo** [comment]
Closed by: https://github.com/DataDog/datadog-sync-cli/pull/216
