### ISSUE TITLE
403 Forbidden after 467634b4

### ISSUE THREAD

**Issue by dhduvall** [DataDog/datadog-sync-cli#301]
I updated this morning and everything stopped working. I got a stream of things like
```
2024-11-07 10:48:27,849 - WARNING - [users - ] - error while running pre-apply hook: 403 Forbidden - {"errors":["Forbidden"]}
2024-11-07 10:48:28,085 - WARNING - [teams - ] - error while running pre-apply hook: 403 Forbidden - {"errors":["Forbidden"]}
```
When I backed off to the previous commit, it started working again. I guess my app key doesn't have permission to write metrics?

Putting a `try`/`except` around those two lines allowed it to work again.

**Comment by skarimo** [comment]
Hello, you are correct. Your app key probably does not have permission to push metrics. Could you try disabling emission by setting `--send-metrics false`?

**Comment by dhduvall** [comment]
Yes, `--send-metrics false` works around the problem. I don't understand why the key doesn't have the permissions—it's created by a user with the `Datadog Admin Role` and has no scopes, and I'd expect that to be able to do everything, including writing metrics, as it's enabled for the role. But I see that the `try`/`except` is better done in `CustomClient.send_metric()`

**Comment by michael-richey** [comment]
This should be resolved now with [PR 307](https://github.com/DataDog/datadog-sync-cli/pull/308) and Release 1.3.0. Please re-open if not.
